// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aylzgwnxwyrtyyvrifjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5bHpnd254d3lydHl5dnJpZmpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODE2MjAsImV4cCI6MjA3MDE1NzYyMH0.I0XD007blCabu-4ZdgoXMOJ0euFoKOG_OLvE_HlWpRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});